sonar.projectKey=mitchins_quokka-test
sonar.organization=mitchins
sonar.sources=Sources
sonar.tests=Tests
sonar.swift.coverage.reportPaths=coverage/unit-coverage.xml,coverage/ui-coverage.xml


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=quokka-test
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Temporary for the initial library bootstrap:
# these new files are intentionally exempt from PR-level coverage until the next
# migration step, where we will enforce coverage in a follow-up cycle.
sonar.coverage.exclusions=Sources/QuokkaTest/**/*.swift,Tests/**/*.swift
